from dataclasses import dataclass
from typing import Literal

GlobalMarketGroup = Literal["indices", "fx", "commodities", "yields"]
ValueKind = Literal["point", "exchange_rate", "price", "yield"]


@dataclass(frozen=True, slots=True)
class ProductDefinition:
    id: str
    group: GlobalMarketGroup
    subgroup: str | None
    name: str
    display_code: str
    source_symbol: str | None
    source_symbols: tuple[str, ...]
    value_kind: ValueKind
    unit: str
    quote_direction: str | None
    precision: int
    origin: str
    market_timezone: str | None
    market_schedule: str
    is_daily: bool = False


PRODUCTS: tuple[ProductDefinition, ...] = (
    ProductDefinition(
        id="global-index.hsi",
        group="indices",
        subgroup="亚洲",
        name="恒生指数",
        display_code="HSI",
        source_symbol="HSI",
        source_symbols=("HSI",),
        value_kind="point",
        unit="点",
        quote_direction=None,
        precision=2,
        origin="eastmoney",
        market_timezone="Asia/Hong_Kong",
        market_schedule="hong-kong",
    ),
    ProductDefinition(
        id="global-index.n225",
        group="indices",
        subgroup="亚洲",
        name="日经225指数",
        display_code="N225",
        source_symbol="N225",
        source_symbols=("N225",),
        value_kind="point",
        unit="点",
        quote_direction=None,
        precision=2,
        origin="eastmoney",
        market_timezone="Asia/Tokyo",
        market_schedule="japan",
    ),
    ProductDefinition(
        id="global-index.kospi",
        group="indices",
        subgroup="亚洲",
        name="韩国综合指数",
        display_code="KOSPI",
        source_symbol="KS11",
        source_symbols=("KS11",),
        value_kind="point",
        unit="点",
        quote_direction=None,
        precision=2,
        origin="eastmoney",
        market_timezone="Asia/Seoul",
        market_schedule="korea",
    ),
    ProductDefinition(
        id="global-index.dji",
        group="indices",
        subgroup="美国",
        name="道琼斯工业指数",
        display_code="DJI",
        source_symbol="DJIA",
        source_symbols=("DJIA",),
        value_kind="point",
        unit="点",
        quote_direction=None,
        precision=2,
        origin="eastmoney",
        market_timezone="America/New_York",
        market_schedule="new-york",
    ),
    ProductDefinition(
        id="global-index.ixic",
        group="indices",
        subgroup="美国",
        name="纳斯达克综合指数",
        display_code="IXIC",
        source_symbol="NDX",
        source_symbols=("NDX",),
        value_kind="point",
        unit="点",
        quote_direction=None,
        precision=2,
        origin="eastmoney",
        market_timezone="America/New_York",
        market_schedule="new-york",
    ),
    ProductDefinition(
        id="global-index.spx",
        group="indices",
        subgroup="美国",
        name="标普500指数",
        display_code="SPX",
        source_symbol="SPX",
        source_symbols=("SPX",),
        value_kind="point",
        unit="点",
        quote_direction=None,
        precision=2,
        origin="eastmoney",
        market_timezone="America/New_York",
        market_schedule="new-york",
    ),
    ProductDefinition(
        id="global-fx.usd-index",
        group="fx",
        subgroup=None,
        name="美元指数",
        display_code="USDIND",
        source_symbol="UDI",
        source_symbols=("UDI",),
        value_kind="point",
        unit="指数点位",
        quote_direction=None,
        precision=3,
        origin="eastmoney",
        market_timezone="Asia/Shanghai",
        market_schedule="fx",
    ),
    ProductDefinition(
        id="global-fx.usd-cnh",
        group="fx",
        subgroup=None,
        name="美元/离岸人民币",
        display_code="USDCNH",
        source_symbol="USDCNH",
        source_symbols=("USDCNH",),
        value_kind="exchange_rate",
        unit="CNH",
        quote_direction="1 USD = X CNH",
        precision=4,
        origin="eastmoney",
        market_timezone="Asia/Shanghai",
        market_schedule="fx",
    ),
    ProductDefinition(
        id="global-fx.hkd-cnh",
        group="fx",
        subgroup=None,
        name="港币/离岸人民币",
        display_code="HKDCNH",
        source_symbol="HKDCNH",
        source_symbols=("HKDCNH",),
        value_kind="exchange_rate",
        unit="CNH",
        quote_direction="1 HKD = X CNH",
        precision=4,
        origin="eastmoney",
        market_timezone="Asia/Shanghai",
        market_schedule="fx",
    ),
    ProductDefinition(
        id="global-commodity.xauusd",
        group="commodities",
        subgroup="伦敦现货",
        name="伦敦金现",
        display_code="XAUUSD",
        source_symbol="XAU",
        source_symbols=("XAU",),
        value_kind="price",
        unit="美元/盎司",
        quote_direction=None,
        precision=2,
        origin="sina",
        market_timezone="Europe/London",
        market_schedule="global-commodity",
    ),
    ProductDefinition(
        id="global-commodity.xagusd",
        group="commodities",
        subgroup="伦敦现货",
        name="伦敦银现",
        display_code="XAGUSD",
        source_symbol="XAG",
        source_symbols=("XAG",),
        value_kind="price",
        unit="美元/盎司",
        quote_direction=None,
        precision=3,
        origin="sina",
        market_timezone="Europe/London",
        market_schedule="global-commodity",
    ),
    ProductDefinition(
        id="global-commodity.gc",
        group="commodities",
        subgroup="纽约期货",
        name="纽约金主连",
        display_code="GC",
        source_symbol="GC00Y",
        source_symbols=("GC00Y",),
        value_kind="price",
        unit="美元/盎司",
        quote_direction=None,
        precision=2,
        origin="eastmoney",
        market_timezone="America/New_York",
        market_schedule="global-commodity",
    ),
    ProductDefinition(
        id="global-commodity.si",
        group="commodities",
        subgroup="纽约期货",
        name="纽约银主连",
        display_code="SI",
        source_symbol="SI00Y",
        source_symbols=("SI00Y",),
        value_kind="price",
        unit="美元/盎司",
        quote_direction=None,
        precision=3,
        origin="eastmoney",
        market_timezone="America/New_York",
        market_schedule="global-commodity",
    ),
    ProductDefinition(
        id="global-commodity.au",
        group="commodities",
        subgroup="国内期货",
        name="沪金主连",
        display_code="AU",
        source_symbol=None,
        source_symbols=(),
        value_kind="price",
        unit="元/克",
        quote_direction=None,
        precision=2,
        origin="sina",
        market_timezone="Asia/Shanghai",
        market_schedule="shfe",
    ),
    ProductDefinition(
        id="global-commodity.ag",
        group="commodities",
        subgroup="国内期货",
        name="沪银主连",
        display_code="AG",
        source_symbol=None,
        source_symbols=(),
        value_kind="price",
        unit="元/千克",
        quote_direction=None,
        precision=0,
        origin="sina",
        market_timezone="Asia/Shanghai",
        market_schedule="shfe",
    ),
    ProductDefinition(
        id="global-commodity.brent",
        group="commodities",
        subgroup="能源",
        name="布伦特原油主连",
        display_code="BRENT",
        source_symbol="B00Y",
        source_symbols=("B00Y",),
        value_kind="price",
        unit="美元/桶",
        quote_direction=None,
        precision=2,
        origin="eastmoney",
        market_timezone="Europe/London",
        market_schedule="global-commodity",
    ),
    ProductDefinition(
        id="global-commodity.cl",
        group="commodities",
        subgroup="能源",
        name="美原油主连",
        display_code="CL",
        source_symbol="CL00Y",
        source_symbols=("CL00Y",),
        value_kind="price",
        unit="美元/桶",
        quote_direction=None,
        precision=2,
        origin="eastmoney",
        market_timezone="America/New_York",
        market_schedule="global-commodity",
    ),
    ProductDefinition(
        id="global-yield.cn1y",
        group="yields",
        subgroup="中国",
        name="中国1年期国债收益率",
        display_code="CN1Y",
        source_symbol="中国1年期国债",
        source_symbols=("中国1年期国债",),
        value_kind="yield",
        unit="%",
        quote_direction=None,
        precision=3,
        origin="sina",
        market_timezone="Asia/Shanghai",
        market_schedule="daily",
        is_daily=True,
    ),
    ProductDefinition(
        id="global-yield.cn10y",
        group="yields",
        subgroup="中国",
        name="中国10年期国债收益率",
        display_code="CN10Y",
        source_symbol="中国10年期国债",
        source_symbols=("中国10年期国债",),
        value_kind="yield",
        unit="%",
        quote_direction=None,
        precision=3,
        origin="sina",
        market_timezone="Asia/Shanghai",
        market_schedule="daily",
        is_daily=True,
    ),
    ProductDefinition(
        id="global-yield.us1y",
        group="yields",
        subgroup="美国",
        name="美国1年期国债收益率",
        display_code="US1Y",
        source_symbol="美国1年期国债",
        source_symbols=("美国1年期国债",),
        value_kind="yield",
        unit="%",
        quote_direction=None,
        precision=3,
        origin="sina",
        market_timezone="America/New_York",
        market_schedule="daily",
        is_daily=True,
    ),
    ProductDefinition(
        id="global-yield.us10y",
        group="yields",
        subgroup="美国",
        name="美国10年期国债收益率",
        display_code="US10Y",
        source_symbol="美国10年期国债",
        source_symbols=("美国10年期国债",),
        value_kind="yield",
        unit="%",
        quote_direction=None,
        precision=3,
        origin="sina",
        market_timezone="America/New_York",
        market_schedule="daily",
        is_daily=True,
    ),
)


PRODUCTS_BY_GROUP: dict[GlobalMarketGroup, tuple[ProductDefinition, ...]] = {
    group: tuple(product for product in PRODUCTS if product.group == group)
    for group in ("indices", "fx", "commodities", "yields")
}

EXPECTED_COUNTS = {group: len(items) for group, items in PRODUCTS_BY_GROUP.items()}

GROUP_LABELS: dict[GlobalMarketGroup, tuple[str, str]] = {
    "indices": ("全球指数", "GLOBAL INDICES"),
    "fx": ("汇率情况", "FX MARKET"),
    "commodities": ("全球商品", "GLOBAL COMMODITIES"),
    "yields": ("国债收益率", "GOVERNMENT YIELDS"),
}
